#!/usr/bin/env bash
# Rick C-137 — Android Bridge one-shot setup (Termux + host)
# =========================================================
# Run this from Termux on the phone OR from a host that has adb.
#
# What it does:
#   1. Ensures adb / termux tools are present
#   2. Enables ADB over TCP (if USB is connected once)
#   3. Forwards DroidBridge MCP port
#   4. Installs Python client deps
#   5. Writes a ready-to-source env file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT/.android_bridge.env"

echo "⚡️  Rick C-137 Android Bridge Setup"

# ---------- detect environment ----------
IN_TERMUX=0
if [[ -n "${TERMUX_VERSION:-}" ]] || [[ -d /data/data/com.termux ]]; then
  IN_TERMUX=1
  echo "→ Detected Termux"
fi

# ---------- packages ----------
if [[ $IN_TERMUX -eq 1 ]]; then
  pkg update -y
  pkg install -y android-tools python python-pip termux-api git
else
  if ! command -v adb >/dev/null; then
    echo "ERROR: adb not found. Install Android platform-tools."
    exit 1
  fi
fi

python3 -m pip install --user -U httpx numpy soundfile 2>/dev/null || true

# ---------- ADB TCP (one-time USB required) ----------
echo ""
echo "If the phone is connected via USB, enabling ADB over TCP on port 5555…"
adb tcpip 5555 2>/dev/null || echo "(skipped – no USB device or already in TCP mode)"

# Try to connect over localhost (works from Termux after tcpip)
adb connect 127.0.0.1:5555 2>/dev/null || true

# ---------- DroidBridge port forward ----------
echo "Forwarding DroidBridge MCP port 8765…"
adb forward tcp:8765 tcp:8765 2>/dev/null || echo "(forward may already exist)"

# ---------- write env file ----------
cat > "$ENV_FILE" <<EOF
# Generated by setup_android_bridge.sh — $(date -Iseconds)
export DROIDBRIDGE_URL="http://127.0.0.1:8765/mcp"
# Paste the bearer token from DroidBridge app → Agent connection → Local MCP
export DROIDBRIDGE_TOKEN=""
export ADB_SERIAL=""
export RICK_ANDROID_BRIDGE="droidbridge"   # or "adb"
EOF

echo ""
echo "✅ Setup complete."
echo ""
echo "Next steps:"
echo "  1. Install DroidBridge APK from https://github.com/zephyr7030/DroidBridge/releases"
echo "  2. Open the app → enable Accessibility + Notification access"
echo "  3. Agent connection → Local MCP → copy the bearer token"
echo "  4. Edit $ENV_FILE and paste the token into DROIDBRIDGE_TOKEN"
echo "  5. source $ENV_FILE"
echo "  6. python $ROOT/device/android_bridge/droidbridge_client.py list-tools"
echo ""
echo "Fallback pure-ADB test:"
echo "  python $ROOT/device/android_bridge/adb_bridge.py devices"
