/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GridRouteImport } from './routes/grid'
import { Route as LabRouteImport } from './routes/lab'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as RestRouteImport } from './routes/rest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const RestRoute = RestRouteImport.update({
  id: '/rest',
  path: '/rest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/lab': typeof LabRoute
  '/oracle': typeof OracleRoute
  '/rest': typeof RestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/lab': typeof LabRoute
  '/oracle': typeof OracleRoute
  '/rest': typeof RestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/lab': typeof LabRoute
  '/oracle': typeof OracleRoute
  '/rest': typeof RestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grid' | '/lab' | '/oracle' | '/rest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grid' | '/lab' | '/oracle' | '/rest'
  id: '__root__' | '/' | '/grid' | '/lab' | '/oracle' | '/rest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GridRoute: typeof GridRoute
  LabRoute: typeof LabRoute
  OracleRoute: typeof OracleRoute
  RestRoute: typeof RestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rest': {
      id: '/rest'
      path: '/rest'
      fullPath: '/rest'
      preLoaderRoute: typeof RestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GridRoute: GridRoute,
  LabRoute: LabRoute,
  OracleRoute: OracleRoute,
  RestRoute: RestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
